force-app/main/default/objects/Lead_Interview__c/Lead_Interview__c.object-meta.xml
<CustomObject>
    <label>Lead Interview</label>
    <nameField>
        <displayFormat>{YY}-{0000}</displayFormat>
        <label>QA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Interview__c/fields/answer__c.field-meta.xml
<CustomField>
    <fullName>answer__c</fullName>
    <label>answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Interviews</relationshipLabel>
    <relationshipName>Lead_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/question__c.field-meta.xml
<CustomField>
    <fullName>question__c</fullName>
    <label>question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadInterviewController.cls
public without sharing class LeadInterviewController {
   
    @AuraEnabled(cacheable=true)
    public static List<Lead_Interview__c> getLeadInterviews(string leadId){
        return [SELECT id, question__c,answer__c FROM  Lead_Interview__c WHERE lead__c =:leadId WITH SECURITY_ENFORCED];
   }

   @AuraEnabled
    public static void deleteLeadInterview(string recordId){
        list<Lead_Interview__c> leadInterviewList = [SELECT Id From Lead_Interview__c WHERE id = : recordId];
        if(!leadInterviewList.isEmpty()){
            delete leadInterviewList;
        }
    }
}