force-app/main/default/objects/Lead_Interview__c/Lead_Interview__c.object-meta.xml
<CustomObject>
    <label>Lead Interview</label>
    <nameField>
        <displayFormat>{YY}-{0000}</displayFormat>
        <label>QA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Interview__c/fields/answer__c.field-meta.xml
<CustomField>
    <fullName>answer__c</fullName>
    <label>answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Interviews</relationshipLabel>
    <relationshipName>Lead_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/question__c.field-meta.xml
<CustomField>
    <fullName>question__c</fullName>
    <label>question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadInterviewControllerTest.cls
/**
 * Author: Ngum buka Fon Nyuydze
 * email: ngumbukafon@gmail.com
 */
@isTest
public class LeadInterviewControllerTest {
    @TestSetup
    static void createLeadInterviews(){
        lead newLead = new Lead(
            LastName = 'test 1',
            Company='Company Test'
        );
      insert newLead;  

      insert new list<Lead_Interview__c>{
        new Lead_Interview__c(
            question__c = 'test 1',
            answer__c ='test 1',
            Lead__c=newLead.id
          ),
        new Lead_Interview__c(
            question__c = 'test 2',
            answer__c ='test 2',
            Lead__c=newLead.id
          )
      };

    }

    @isTest 
    static void deleteLeadInterviewTest(){
        list<lead> testLead = [SELECT id FROM Lead];
        list<Lead_Interview__c> testLeadInterview = [SELECT id, answer__c, question__c FROM Lead_Interview__c WHERE lead__c =:String.valueOf(testLead[0].id)];
        id recordId = testLeadInterview[0].id;
        System.assertEquals(2, testLeadInterview.size());
        LeadInterviewController.deleteLeadInterview(String.valueOf(recordId));
        
        testLeadInterview = [SELECT id, answer__c, question__c FROM Lead_Interview__c WHERE lead__c =:String.valueOf(testLead[0].id)];

        System.assertEquals(1, testLeadInterview.size());
    }

    @isTest 
    static void getLeadInterviewsTest(){
        list<lead> testLead = [SELECT id FROM Lead];
        list<Lead_Interview__c> testLeadInterview  = LeadInterviewController.getLeadInterviews(String.valueOf(testLead[0].id));
        System.assertEquals(2, testLeadInterview.size());
    }
}