force-app/main/default/objects/Lead_Interview__c/Lead_Interview__c.object-meta.xml
<CustomObject>
    <label>Lead Interview</label>
    <nameField>
        <displayFormat>{YY}-{0000}</displayFormat>
        <label>QA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Interview__c/fields/answer__c.field-meta.xml
<CustomField>
    <fullName>answer__c</fullName>
    <label>answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Interviews</relationshipLabel>
    <relationshipName>Lead_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/question__c.field-meta.xml
<CustomField>
    <fullName>question__c</fullName>
    <label>question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadManagerTest.cls
/**
 * author: Ngum Buka Fon Nyuydze
 * organisation: Hi Corp
 * email: ngumbukafon@gmail.com
 * created-on: 11/01/2023
 * Description: Test the lead creation process
 */

@isTest
public without sharing class LeadManagerTest {
   @isTest static void createLeadTest(){
    RestRequest request = new RestRequest();
    request.requestUri ='https://yourInstance.my.salesforce.com/services/apexrest/Lead/v1/';
    request.httpMethod = 'POST';
    request.addHeader('Content-Type', 'application/json');
    String body = '{"firstName": "Test", "lastName": "Test2", "address": "123 Main St", "city": "USAville","stateProvince": "PA","postalCode": "12345","primaryPhone": "5558675309","email": "lontee111930@gmail.com","leadOid": 135911130,"leadSource": "HomeAdvisor","interview": [{"question": "What kind of location is this?","answer": "Home/Residence"}, {"question": "Request Stage","answer": "Ready to Hire"}, {"question": "Desired Completion Date","answer": "Within 1 week"}]}';

    request.requestBody = Blob.valueOf(body);

    RestContext.request = request;

    
    LeadManager.createLead();
    
    list<lead> newLead = [SELECT id, firstname, lastname, email FROM Lead];
    list<Lead_Interview__c> newLeadInterviewList = [SELECT id FROM Lead_Interview__c ];
    System.assertEquals(1, newLead.size());
    System.assertEquals(3, newLeadInterviewList.size());

   }
   @isTest static void createLeadWithExistingInterviewsAndLeadWithEmailTest(){
    RestRequest request = new RestRequest();
    request.requestUri ='https://yourInstance.my.salesforce.com/services/apexrest/Lead/v1/';
    request.httpMethod = 'POST';
    request.addHeader('Content-Type', 'application/json');
    String body = '{"firstName": "Test", "lastName": "Test2", "address": "123 Main St", "city": "USAville","stateProvince": "PA","postalCode": "12345","primaryPhone": "5558675309","email": "lontee111930@gmail.com","leadOid": 135911130,"leadSource": "HomeAdvisor","interview": [{"question": "What kind of location is this?","answer": "Home/Residence"}, {"question": "Request Stage","answer": "Ready to Hire"}, {"question": "Desired Completion Date","answer": "Within 1 week"}]}';

    request.requestBody = Blob.valueOf(body);

    RestContext.request = request;
    LeadManager.createLead();
     body = '{"firstName": "Test", "lastName": "Test2", "address": "123 Main St", "city": "USAville","stateProvince": "PA","postalCode": "12345","primaryPhone": "5558675309","email": "lontee111930@gmail.com","leadOid": 135911130,"leadSource": "HomeAdvisor","interview": [{"question": "What kind of location is this? 1","answer": "Home/Residence"}]}';
    LeadManager.createLead();

    list<lead> newLead = [SELECT id, firstname, lastname, email FROM Lead];
    list<Lead_Interview__c> newLeadInterviewList = [SELECT id, question__c, answer__c,Lead__c FROM Lead_Interview__c ];
    System.assertEquals(1, newLead.size());

   }
   @isTest static void createLeadWithWrongJsonTest(){
    RestRequest request = new RestRequest();
    request.requestUri ='https://yourInstance.my.salesforce.com/services/apexrest/Lead/v1/';
    request.httpMethod = 'POST';
    request.addHeader('Content-Type', 'application/json');
    String body = '"firstName": "Test", "lastName": "Test2", "address": "123 Main St", "city": "USAville","stateProvince": "PA","postalCode": "12345","primaryPhone": "5558675309","email": "lontee111930@gmail.com","leadOid": 135911130,"leadSource": "HomeAdvisor","interview": [{"question": "What kind of location is this?","answer": "Home/Residence"}, {"question": "Request Stage","answer": "Ready to Hire"}, {"question": "Desired Completion Date","answer": "Within 1 week"}]}';

    request.requestBody = Blob.valueOf(body);
    RestContext.request = request;
    LeadManager.createLead();

    list<lead> newLead = [SELECT id, firstname, lastname, email FROM Lead];
    list<Lead_Interview__c> newLeadInterviewList = [SELECT id FROM Lead_Interview__c ];
    System.assertEquals(0, newLead.size());
    System.assertEquals(0, newLeadInterviewList.size());

   }

}