force-app/main/default/objects/Lead/fields/leadOid__c.field-meta.xml
<CustomField>
    <fullName>leadOid__c</fullName>
    <label>leadOid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/Lead_Interview__c.object-meta.xml
<CustomObject>
    <label>Lead Interview</label>
    <nameField>
        <displayFormat>{YY}-{0000}</displayFormat>
        <label>QA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Interview__c/fields/answer__c.field-meta.xml
<CustomField>
    <fullName>answer__c</fullName>
    <label>answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Interviews</relationshipLabel>
    <relationshipName>Lead_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Interview__c/fields/question__c.field-meta.xml
<CustomField>
    <fullName>question__c</fullName>
    <label>question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadWithInterviewCreator.cls
/**
 * author: Ngum Buka Fon Nyuydze
 * organisation: Hi Corp
 * email: ngumbukafon@gmail.com
 * created-on: 11/01/2023
 * Description: Helper class for generating lead and lead interview Questions from JSON string
 */

public without sharing class LeadWithInterviewCreator {
    public static void generateLeadInterview(LeadWithInterview instance){
        lead leadInstance = new lead();
        list<lead> existingLeadList  = [SELECT id, email FROM Lead WHERE email=:instance.email];
        if(!existingLeadList.isEmpty()){
            leadInstance = existingLeadList[0];
        }
        leadInstance.LastName = instance.lastName;
        leadInstance.FirstName = instance.firstName;
        leadInstance.City = instance.city;
        leadInstance.State = instance.stateProvince;
        leadInstance.PostalCode = instance.postalCode;
        leadInstance.Phone = instance.primaryPhone;
        leadInstance.Email = instance.email;
        leadInstance.leadOid__c = instance.leadOid;
        leadInstance.LeadSource = instance.leadSource;
        leadInstance.Company = 'Company Name';

        upsert leadInstance;

        list<Lead_Interview__c> questionAndAnswers = new list<Lead_Interview__c>();

        list<Lead_Interview__c> existingInterviewInstanceList  = [SELECT id, question__c FROM Lead_Interview__c WHERE Lead__c=:leadInstance.id];

        for(Interview interviewInstance : instance.interview ){
            Lead_Interview__c singleInterview = new Lead_Interview__c();
            
            if(!existingInterviewInstanceList.isEmpty()){
                for(Lead_Interview__c existingInterview:existingInterviewInstanceList){
                    if(interviewInstance.question.toUpperCase() == existingInterview.question__c.toUpperCase()){
                        singleInterview = existingInterview;
                        singleInterview.id = existingInterview.id;
                    }else{
                        singleInterview.question__c = interviewInstance.question;
                    }
                }
            }
            else{
                singleInterview.question__c = interviewInstance.question; 
            }
            singleInterview.Lead__c = leadInstance.Id;
            singleInterview.answer__c = interviewInstance.answer;
            questionAndAnswers.add(singleInterview);
        }

       if(!questionAndAnswers.isEmpty()){
        upsert questionAndAnswers;
       }
    }


    public static void generateLeadInterview(list<LeadWithInterview> instanceList){
        

    }
}